# yaml 配置
version: '3'
services:
  cassandra:
    image: "cassandra:latest"
    #container_name: cassandra
    ports:
      - "9042:9042"
    # networks:
    #   - backend
          

  web:
    image: "python:3.6.8"
    #container_name: flask
    links:
      - cassandra
    build: .
    ports:
      - "5000:5000"
    # networks:
    #   - mynetwork

# networks:
#   backend:
#   mynetwork:


